backend:
  name: github
  repo: claylabel/labelclay       # your GitHub username/repo
  branch: main                    # or your default branch
  auth_type: token                # tell CMS to use personal access token login
  squash_merges: true             # optional, better commit history
  # optional: open_authoring: false

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "store"
    label: "Store"
    folder: "_data/store"
    create: true
    format: "json"
    extension: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }

  - name: "releases"
    label: "Releases"
    folder: "_data/releases"
    create: true
    format: "json"
    extension: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Artist", name: "artist", widget: "string" }
      - { label: "Cover", name: "cover", widget: "image" }
      - { label: "Link", name: "link", widget: "string" }
